In [1]:
import numpy as np
from sklearn import linear_model as lm

F, N = map(int, input().split())
train = np.array([input().split() for _ in range(N)], float)
T = int(input())
test = np.array([input().split() for _ in range(T)], float)

mod = lm.LinearRegression()
mod.fit(train[:, :-1], train[:, -1])
ymod = mod.predict(test)
print(*ymod, sep='\n')

2 7
0.18 0.89 109.85
1.0 0.26 155.72
0.92 0.11 137.66
0.07 0.37 76.17
0.85 0.16 139.75
0.99 0.41 162.6
0.87 0.47 151.77
4
0.49 0.18
0.57 0.83
0.56 0.64
0.76 0.18
105.21455835106944
142.67095130729922
132.93605469124694
129.70175404502453


In [ ]:
0.18 0.89 109.85
1.0 0.26 155.72
0.92 0.11 137.66
0.07 0.37 76.17
0.85 0.16 139.75
0.99 0.41 162.6
0.87 0.47 151.77



0.49 0.18
0.57 0.83
0.56 0.64
0.76 0.18

In [2]:
N=7
train = np.array([input().split() for _ in range(N)], float)
print(train)

0.18 0.89 109.85
1.0 0.26 155.72
0.92 0.11 137.66
0.07 0.37 76.17
0.85 0.16 139.75
0.99 0.41 162.6
0.87 0.47 151.77
[[1.8000e-01 8.9000e-01 1.0985e+02]
 [1.0000e+00 2.6000e-01 1.5572e+02]
 [9.2000e-01 1.1000e-01 1.3766e+02]
 [7.0000e-02 3.7000e-01 7.6170e+01]
 [8.5000e-01 1.6000e-01 1.3975e+02]
 [9.9000e-01 4.1000e-01 1.6260e+02]
 [8.7000e-01 4.7000e-01 1.5177e+02]]


In [5]:
import numpy as np
from sklearn import linear_model as lm

F,N = map(int, input().split())
train = np.array([input().split() for i in range(N)],float)
T = int(input())
test = np.array([input().split() for i in range(T)],float)
mod = lm.LinearRegression()
mod.fit(train[:,:-1],train[:,-1])
ymod = mod.predict(test)

for i in ymod:
    print(round(i,2))
print(ymod)

2 7
0.18 0.89 109.85
1.0 0.26 155.72
0.92 0.11 137.66
0.07 0.37 76.17
0.85 0.16 139.75
0.99 0.41 162.6
0.87 0.47 151.77
4
0.49 0.18
0.57 0.83
0.56 0.64
0.76 0.18
105.215
142.671
132.936
129.702
[105.21455835 142.67095131 132.93605469 129.70175405]
