In [4]:
def solution(A):
    min_num = 0 
    my_list = list(A)
    for i in range(1,(max(my_list))):
        if i in my_list:
            pass
        elif i not in my_list:
            print (i)
            break
A=[-1,2,4,9,5]
(solution(A))

In [5]:
def solution(A):
    A.sort()
    N = len(A)
    
    i = 0
    previous = 0
    while i < N:
        current = A[i]

        if current > 0:
            if current > previous + 1:
                return previous + 1
            else:
                previous = current
        
        i += 1
    
    return max(previous+1, current+1)
A=[-1,2,4,9,5]
solution(A)

1

In [ ]:
import pandas as pd
import scipy
import math
# from scipy.stats import chisqprob
# from scipy import chi2
from scipy import stats
import math
from math import sqrt
from itertools import product
import itertools
from itertools import combinations
from scipy.stats import chi2


df= pd.read_excel("C:/Users/DOTSC75/Desktop/Car_data.xlsx")
df1= df[['buying', 'mainta', 'doors', 'persons', 'lug_bot', 'safety']]

df1.head(5)

# columns= df.columns
# df.columns
# df.at[2,'buying']
ADC=dict()
N_Gain=dict()
S_U=dict()
M_I= dict()

for var1 in df1.columns:
    p = df[var1].unique()
#     print(type(var1))
#     x_cols = [x for x in df.columns if x != var1]
#     print (var1)
#     for var2 in x_cols:
    q = df['acceptability'].unique()
#         print(var2)
    result=[]
    for i in range(len(p)):
        row=[]
        
        for j in range(len(q)):
            count=0
                
            for d in range(0, len(df)):
                if((df.at[d,var1]==p[i]) & (df.at[d,'acceptability']==q[j])):
                    count=count+1

            row.append(count)
   
        result.append(row)

    np.array(result).reshape(len(p),len(q) )
    
    total= sum(map(sum, result))
 
    p_matrix=[]
    for i in range (len(p)):
        p_row=[]
        for j in range(len(q)):
            prb= (result[i][j])/total
            p_row.append(prb)
        p_matrix.append(p_row)
    p1_mat=np.array(p_matrix).reshape(len(p),len(q) )
  
    H_f=0
    for i in range (len(p)):
        e=(sum(p1_mat[i,:]))
        if e!=0:            
            H_f= H_f+ (e * math.log2(e**(-1)))
    
    H_c=0
    for i in range (len(q)):
        g=sum(p1_mat[:,i])
        if g!=0:            
            H_c= H_c+ (g * math.log2(g**(-1)))


    H_cf=0
    for i in range (len(p)):
        for j in range(len(q)):
            k= (p1_mat[i][j])
            if k!=0:
                H_cf= H_cf+ (k * math.log2(k**(-1)))

    I_cf= H_f + H_c -H_cf   
    adc= I_cf/H_c
    ADC[var1]=adc    
    n_gain=I_cf/H_f
    N_Gain[var1]=n_gain    
    s_u=2*I_cf/(H_c+H_f)
    S_U[var1]=s_u    
    M_I[var1]=I_cf    
ADC_s = {k: v for k, v in sorted(ADC.items(), key=lambda x: x[1], reverse=True)}    
N_Gain_s = {k: v for k, v in sorted(N_Gain.items(), key=lambda x: x[1], reverse=True)} 
S_U_s = {k: v for k, v in sorted(S_U.items(), key=lambda x: x[1], reverse=True)} 
M_I_s = {k: v for k, v in sorted(M_I.items(), key=lambda x: x[1], reverse=True)}  

print('Asymetric Dependency Coefficient RANK:')                
print(ADC_s)
print('Normalized Gain RANK:')  
print(N_Gain_s)
print('Symmetrical Uncertainty RANK:')  
print(S_U_s)
print('Mutual Information RANK:')  
print(M_I_s)

In [8]:
import numpy as np

def calc_MI(X,Y,bins):

   c_XY = np.histogram2d(X,Y,bins)[0]
   c_X = np.histogram(X,bins)[0]
   c_Y = np.histogram(Y,bins)[0]

   H_X = shan_entropy(c_X)
   H_Y = shan_entropy(c_Y)
   H_XY = shan_entropy(c_XY)

   MI = H_X + H_Y - H_XY
   return MI

def shan_entropy(c):
    c_normalized = c / float(np.sum(c))
    c_normalized = c_normalized[np.nonzero(c_normalized)]
    H = -sum(c_normalized* np.log2(c_normalized))  
    return H

A = np.array([[ 2.0,  140.0,  128.23, -150.5, -5.4  ],
              [ 2.4,  153.11, 130.34, -130.1, -9.5  ],
              [ 1.2,  156.9,  120.11, -110.45,-1.12 ]])

bins = 5 # ?
n = A.shape[1]
matMI = np.zeros((n, n))

for ix in np.arange(n):
    for jx in np.arange(ix+1,n):
        matMI[ix,jx] = calc_MI(A[:,ix], A[:,jx], bins)
        


In [16]:
arr = np.array([[ 2.0,  140.0,  128.23, -150.5, -5.4  ],
              [ 2.4,  153.11, 130.34, -130.1, -9.5  ],
              [ 1.2,  156.9,  120.11, -110.45,-1.12 ]])


def s_ent(c):
    c_normalized = c / float(np.sum(c))
    c_normalized = c_normalized[np.nonzero(c_normalized)]
    H = -sum(c_normalized* np.log2(c_normalized))  
    return H

def Mutual_Info(X,Y,bins):

   c_XY = np.histogram2d(X,Y,bins)[0]
   c_X = np.histogram(X,bins)[0]
   c_Y = np.histogram(Y,bins)[0]

   H_X = s_ent(c_X)
   H_Y = s_ent(c_Y)
   H_XY = s_ent(c_XY)

   Mutual_information = H_X + H_Y - H_XY
   return Mutual_information




bins = 5
n = arr.shape[1]
matrix_Mutual_Inf = np.zeros((n, n))
for ik in np.arange(n):
    for jk in np.arange(ik+1,n):
        matrix_Mutual_Inf[ik,jk] = Mutual_Info(arr[:,ik], arr[:,jk], bins)
        
print(matrix_Mutual_Inf)
        


[[0.        1.5849625 1.5849625 1.5849625 1.5849625]
 [0.        0.        1.5849625 1.5849625 1.5849625]
 [0.        0.        0.        1.5849625 1.5849625]
 [0.        0.        0.        0.        1.5849625]
 [0.        0.        0.        0.        0.       ]]


In [ ]:
# Starting code

import numpy as np

def mutual_information(arr):
    
    def s_ent(c):
        c_normalized = c / float(np.sum(c))
        c_normalized = c_normalized[np.nonzero(c_normalized)]
        H = -sum(c_normalized* np.log2(c_normalized))  
        return H

    def Mutual_Info(X,Y,bins):
        c_XY = np.histogram2d(X,Y,bins)[0]
        c_X = np.histogram(X,bins)[0]
        c_Y = np.histogram(Y,bins)[0]
        
        H_X = s_ent(c_X)
        H_Y = s_ent(c_Y)
        H_XY = s_ent(c_XY)
        Mutual_information = H_X + H_Y - H_XY
        return Mutual_information




    bins = 5
    n = arr.shape[1]
    matrix_Mutual_Inf = np.zeros((n, n))
    for ik in np.arange(n):
        for jk in np.arange(ik+1,n):
            matrix_Mutual_Inf[ik,jk] = Mutual_Info(arr[:,ik], arr[:,jk], bins)
    return matrix_Mutual_Inf


In [20]:
arr = np.array([[ 2.0,  140.0,  128.23, -150.5, -5.4  ],
              [ 2.4,  153.11, 130.34, -130.1, -9.5  ],
              [ 1.2,  156.9,  120.11, -110.45,-1.12 ]])
bins = len(arr[0])
print(bins)
print(arr.shape[1])

5
5
